### ISSUE TITLE
Entities burn with the wrong fire color when standing on the edge of a block that is on fire

### ISSUE THREAD

**Issue by CerbTheOne** [nyancermc/AffectedFire#1]
If an entity stands on a block enough so that it burns but not enough for the coordinates to change, it will burn using the color of the last fire it came in contact with. Check the images below for a little more information.

In this image I'm standing on the soul fire, but I'm burning red. Take a look at the coordinates.
![image](https://user-images.githubusercontent.com/22283069/112698499-90ae0a00-8e68-11eb-9ec1-2869689677f6.png)

As soon as my coordinates change to the block the fire is actually on, I start burning blue.
![image](https://user-images.githubusercontent.com/22283069/112698549-a58a9d80-8e68-11eb-88b1-e28a71111760.png)

Same happens if I stand on the soul fire first
![image](https://user-images.githubusercontent.com/22283069/112698768-2cd81100-8e69-11eb-9126-37c49ea449fb.png)
![image](https://user-images.githubusercontent.com/22283069/112698801-3c575a00-8e69-11eb-86ac-074ce7416e95.png)

**Comment by nyancermc** [comment]
thanks for report!
this bug is fixed in 1.16.5-1.0.1
